### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by HappySinha** [mohsenzamani22/video_player#1]
When increasing minSdkVersion 21 to minSdkVersion 24 then the video does not play and showed this Error.
No implementation found for method listen on channel video/videoEvents0

    `The following MissingPluginException was thrown while activating platform stream on channel video/videoEvents0:
      MissingPluginException(No implementation found for method listen on channel video/videoEvents0)

    When the exception was thrown, this was the stack: 
     #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
    <asynchronous suspension>
    #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:506:9)
    <asynchronous suspension>`

How can solve this Error?

**Comment by Mhwmd** [comment]
did you try hot restart?

**Comment by HappySinha** [comment]
> did you try hot restart?

Yes, I'm trying this but didn't solve it.
